### ISSUE TITLE
CLI run command throws a TypeError

### ISSUE THREAD

**Issue by mcheng-caring** [contentful-userland/cf-content-types-generator#159]
## Description

The run command for ``cf-content-types-generator` no longer works as of the v2.1.0 release. This was working in v2.0.1.

## Environment

Version: `cf-content-types-generator@2.1.0`
OS: macOS Monterey (12.3)
Shell: zsh

Last known working version: `cf-content-types-generator@2.0.1`

## Reproduction Steps

Either:

1. From your shell, run `npx cf-content-types-generator -s YOUR_SPACE -e YOU_ENV -t YOUR_TOKEN -o __cf_generated__`
2. No files are generated and the following error is thrown:

```
    TypeError: (0 , contentful_export_1.default) is not a function
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Or:

1. Install `cf-content-types-generator` per README instructions.
2. Have a run script in `package.json` with: `cf-content-types-generator -s YOUR_SPACE -e YOU_ENV -t YOUR_TOKEN -o __cf_generated__`
3. Execute run script command. E.g., `yarn get-cf-types` in my case.
4. No files are generated and the same error as above is thrown.

**Comment by marcolink** [comment]
Thanks @mcheng-caring 

I will look into it!

**Comment by jeremydouglas** [comment]
Same here, `2.0.2` works for me, but something broke in `2.1.0`

**Comment by marcolink** [comment]
@mcheng-caring @jeremydouglas thanks again for reporting!

it's fixed with version [`2.2.2`](https://github.com/contentful-userland/cf-content-types-generator/releases/tag/v2.2.2)

**Comment by raulfdm** [comment]
@marcolink , I've installed the latest version (2.4.1) and I'm getting this error again.

Should I open another issue?

**Comment by marcolink** [comment]
I have an idea ...

**Comment by marcolink** [comment]
https://github.com/contentful-userland/cf-content-types-generator/pull/195 🤞

**Comment by raulfdm** [comment]
Thanks @marcolink 🙌
